module.exports = [
  "Stairway To Heaven Led Zeppelin",
  "Bohemian Rhapsody Queen",
  "Hotel California Eagles",
  "Sweet Home Alabama Lynyrd Skynyrd",
  "The Happiest Days Of Our Lives /Another Brick In The Wall, Pt. 2 Pink Floyd",
  "Come Together Beatles",
  "Baba O'Riley Who",
  "Black Dog Led Zeppelin",
  "(I Can't Get No) Satisfaction Rolling Stones",
  "Sweet Emotion Aerosmith",
  "Layla Derek & The Dominos",
  "Free Bird Lynyrd Skynyrd",
  "Hey Jude Beatles",
  "Back In Black AC/DC",
  "Sympathy For The Devil Rolling Stones",
  "Sweet Child O' Mine Guns N' Roses",
  "Kashmir Led Zeppelin",
  "Won't Get Fooled Again Who",
  "Dream On Aerosmith",
  "We Will Rock You (We Are The Champions) Queen",
  "All Along The Watchtower Jimi Hendrix",
  "You Shook Me All Night Long AC/DC",
  "Don't Stop Believin' Journey",
  "Whole Lotta Love Led Zeppelin",
  "Carry On Wayward Son Kansas",
  "Tom Sawyer Rush",
  "More Than A Feeling Boston",
  "Runnin' With The Devil Van Halen",
  "Crazy Train Ozzy Osbourne",
  "Rock And Roll Led Zeppelin",
  "Money Pink Floyd",
  "Smoke On The Water Deep Purple",
  "Live And Let Die Paul McCartney",
  "Walk This Way Aerosmith",
  "Light My Fire Doors",
  "Purple Haze Jimi Hendrix",
  "Livin' On A Prayer Bon Jovi",
  "Let It Be Beatles",
  "Jump Van Halen",
  "Imagine John Lennon",
  "Spirit Of Radio Rush",
  "Ramble On Led Zeppelin",
  "Gimme Shelter Rolling Stones",
  "Piano Man Billy Joel",
  "Highway To Hell AC/DC",
  "Pride (In the Name of Love) U2",
  "Foreplay/Long Time Boston",
  "Pour Some Sugar On Me Def Leppard",
  "You Can't Always Get What You Want Rolling Stones",
  "Eruption/You Really Got Me Van Halen",
  "Pinball Wizard Who",
  "The Boys Are Back In Town Thin Lizzy",
  "Born To Run Bruce Springsteen",
  "Comfortably Numb Pink Floyd",
  "Rock And Roll All Nite Kiss",
  "Roadhouse Blues Doors",
  "Go Your Own Way Fleetwood Mac",
  "Paradise By The Dashboard Light Meat Loaf",
  "Enter Sandman Metallica",
  "In The Air Tonight Phil Collins",
  "Just What I Needed Cars",
  "Life In The Fast Lane Eagles",
  "(Don't Fear) The Reaper Blue Öyster Cult",
  "Welcome To The Jungle Guns N' Roses",
  "Barracuda Heart",
  "Behind Blue Eyes Who",
  "Photograph Def Leppard",
  "Juke Box Hero Foreigner",
  "Revolution Beatles",
  "Cocaine Eric Clapton",
  "Karn Evil 9: 1St Impression, Pt. 2 Emerson, Lake & Palmer",
  "Riders On The Storm Doors",
  "Simple Man Lynyrd Skynyrd",
  "Paranoid Black Sabbath",
  "Immigrant Song Led Zeppelin",
  "Free Fallin' Tom Petty",
  "My Generation Who",
  "I Love Rock N Roll Joan Jett",
  "Night Moves Bob Seger",
  "Limelight Rush",
  "Jumpin' Jack Flash Rolling Stones",
  "Under Pressure Queen",
  "Brain Damage/Eclipse Pink Floyd",
  "Runnin' Down A Dream Tom Petty",
  "Radar Love Golden Earring",
  "Smells Like Teen Spirit Nirvana",
  "Born To Be Wild Steppenwolf",
  "Summer Of '69 Bryan Adams",
  "Who Are You Who",
  "Hells Bells AC/DC",
  "New Year's Day U2",
  "Paint It Black Rolling Stones",
  "Panama Van Halen",
  "Iron Man Black Sabbath",
  "Paradise City Guns N' Roses",
  "Over The Hills And Far Away Led Zeppelin",
  "Rocky Mountain Way Joe Walsh",
  "Time Pink Floyd",
  "The Joker Steve Miller",
  "Foxey Lady Jimi Hendrix",
  "Life's Been Good Joe Walsh",
  "Sunshine Of Your Love Cream",
  "The Stroke Billy Squier",
  "Rock The Casbah Clash",
  "Come Sail Away Styx",
  "Going To California Led Zeppelin",
  "Bennie And The Jets Elton John",
  "Roxanne Police",
  "Space Oddity David Bowie",
  "I Want You To Want Me Cheap Trick",
  "Jack & Diane John Mellencamp",
  "Blinded By The Light Manfred Mann",
  "White Wedding Billy Idol",
  "Take It Easy Eagles",
  "Another One Bites The Dust Queen",
  "Turn The Page Bob Seger",
  "Jamie's Cryin' Van Halen",
  "Alive Pearl Jam",
  "Heartbreaker/Livin' Loving Maid Led Zeppelin",
  "Honky Tonk Women Rolling Stones",
  "Sultans Of Swing Dire Straits",
  "Rock'N Me Steve Miller",
  "Turn The Page Metallica",
  "L.A Woman Doors",
  "Fortunate Son Creedence Clearwater Revival",
  "Magic Man Heart",
  "Truckin' Grateful Dead",
  "Rock Of Ages Def Leppard",
  "Wish You Were Here Pink Floyd",
  "Roundabout Yes",
  "Sharp Dressed Man ZZ Top",
  "For Those About To Rock (We Salute You) AC/DC",
  "Cold As Ice Foreigner",
  "Dance The Night Away Van Halen",
  "Closer To The Heart Rush",
  "Girls, Girls, Girls Mötley Crüe",
  "Dazed And Confused Led Zeppelin",
  "Band On The Run Paul McCartney",
  "Centerfold J. Geils Band",
  "Can't You See Marshall Tucker Band",
  "Miss You Rolling Stones",
  "Dirty Deeds Done Dirt Cheap AC/DC",
  "Rebel Yell Billy Idol",
  "Feel Like Makin' Love Bad Company",
  "My Sweet Lord George Harrison",
  "White Room Cream",
  "Why Can't This Be Love Van Halen",
  "You Give Love A Bad Name Bon Jovi",
  "With Or Without You U2",
  "Double Vision Foreigner",
  "Tush ZZ Top",
  "Bad To The Bone George Thorogood",
  "Brown Eyed Girl Van Morrison",
  "Come Together Aerosmith",
  "Peace Of Mind Boston",
  "American Girl Tom Petty",
  "Mother Pink Floyd",
  "Thank You Led Zeppelin",
  "Saturday Night Special Lynyrd Skynyrd",
  "Cinnamon Girl Neil Young",
  "Somebody To Love Queen",
  "Any Way You Want It Journey",
  "Empty Spaces/Young Lust Pink Floyd",
  "The Chain Fleetwood Mac",
  "Let's Go Cars",
  "D'yer Ma'ker Led Zeppelin",
  "T.N.T. AC/DC",
  "In Your Eyes Peter Gabriel",
  "Woman From Tokyo Deep Purple",
  "Message In A Bottle Police",
  "Hey Joe Jimi Hendrix",
  "Money For Nothing Dire Straits",
  "Dancing In The Street Van Halen",
  "It's Only Rock And Roll Rolling Stones",
  "Jet Airliner Steve Miller",
  "That's All Genesis",
  "Gimme Three Steps Lynyrd Skynyrd",
  "Long Live Rock Who",
  "Legs ZZ Top",
  "Break On Through Doors",
  "The Boys Of Summer Don Henley",
  "Feels Like The First Time Foreigner",
  "Babe I'm Gonna Leave You Led Zeppelin",
  "Good Times Roll Cars",
  "Already Gone Eagles",
  "I Wanna Be Sedated Ramones",
  "Changes David Bowie",
  "Where The Streets Have No Name U2",
  "Hard To Handle Black Crowes",
  "Renegade Styx",
  "Burnin' For You Blue Öyster Cult",
  "Wanted Dead Or Alive Bon Jovi",
  "Start Me Up Rolling Stones",
  "Hey You Pink Floyd",
  "Mississippi Queen Mountain",
  "Rag Doll Aerosmith",
  "Ain't Talkin' 'Bout Love Van Halen",
  "Ramblin' Man Allman Brothers Band",
  "Every Breath You Take Police",
  "Tuesday's Gone Lynyrd Skynyrd",
  "Houses Of The Holy Led Zeppelin",
  "Rock You Like A Hurricane Scorpions",
  "Mama I'm Coming Home Ozzy Osbourne",
  "School's Out Alice Cooper",
  "Wheel In The Sky Journey",
  "Freewill Rush",
  "Beast Of Burden Rolling Stones",
  "Home Sweet Home Mötley Crüe",
  "Blue Collar Man Styx",
  "Here I Go Again Whitesnake",
  "Aqualung Jethro Tull",
  "And The Cradle Will Rock... Van Halen",
  "Bad Company Bad Company",
  "Lola Kinks",
  "Thunderstruck AC/DC",
  "Born In The U.S.A. Bruce Springsteen",
  "Run Like Hell Pink Floyd",
  "Old Time Rock And Roll Bob Seger",
  "Lonely Is The Night Billy Squier",
  "Surrender Cheap Trick",
  "Nothing Else Matters Metallica",
  "You've Got Another Thing Comin' Judas Priest",
  "Bye Bye Love Cars",
  "You Better You Bet Who",
  "Jeremy Pearl Jam",
  "Hey Hey What Can I Do Led Zeppelin",
  "I Still Haven't Found What I'm Looking For U2",
  "Interstate Love Song Stone Temple Pilots",
  "Take It On The Run REO Speedwagon",
  "We're Not Gonna Take It Twisted Sister",
  "Fat Bottomed Girls Queen",
  "La Grange ZZ Top",
  "Heartbreaker Pat Benatar",
  "Beautiful Girls Van Halen",
  "Brown Sugar Rolling Stones",
  "You Really Got Me Kinks",
  "Who Made Who AC/DC",
  "Give A Little Bit Supertramp",
  "Solsbury Hill Peter Gabriel",
  "Pride And Joy Stevie Ray Vaughan",
  "You Ain't Seen Nothing Yet Bachman-Turner Overdrive",
  "Separate Ways Journey",
  "Midnight Rider Allman Brothers Band",
  "Close My Eyes Forever Lita Ford F/Ozzy Osbourne",
  "Fool In The Rain Led Zeppelin",
  "Head Games Foreigner",
  "Werewolves Of London Warren Zevon",
  "Love In An Elevator Aerosmith",
  "Sister Christian Night Ranger",
  "Learning To Fly Pink Floyd",
  "Don't You (Forget About Me) Simple Minds",
  "Everybody Wants You Billy Squier",
  "Wonderful Tonight Eric Clapton",
  "Sunday Bloody Sunday U2",
  "What I Like About You Romantics",
  "Bargain Who",
  "The Unforgiven Metallica",
  "Magic Carpet Ride Steppenwolf",
  "Losing My Religion R.E.M.",
  "Rock & Roll Never Forgets Bob Seger",
  "No One Like You Scorpions",
  "Breakdown Tom Petty",
  "Under The Bridge Red Hot Chili Peppers",
  "Walk Of Life Dire Straits",
  "Dust In The Wind Kansas",
  "Killer Queen Queen",
  "Dr. Feelgood Mötley Crüe",
  "Small Town John Mellencamp",
  "Cat Scratch Fever Ted Nugent",
  "Rock 'N' Roll Fantasy Bad Company",
  "I Hate Myself For Loving You Joan Jett",
  "When The Levee Breaks Led Zeppelin",
  "Edge Of Seventeen Stevie Nicks",
  "Come As You Are Nirvana",
  "Hot Blooded Foreigner",
  "One Way Or Another Blondie",
  "I'll Wait Van Halen",
  "Shoot To Thrill AC/DC",
  "Wrapped Around Your Finger Police",
  "Hit Me With Your Best Shot Pat Benatar",
  "Don't Bring Me Down Electric Light Orchestra",
  "Call Me The Breeze Lynyrd Skynyrd",
  "Listen To The Music Doobie Brothers",
  "Too Late For Love Def Leppard",
  "Every Rose Has Its Thorn Poison",
  "My Best Friend's Girl Cars",
  "Locomotive Breath Jethro Tull",
  "Intruder/Oh, Pretty Woman Van Halen",
  "Cum On Feel The Noize Quiet Riot",
  "Detroit Rock City Kiss",
  "You're My Best Friend Queen",
  "Burning Down The House Talking Heads",
  "Goodbye Stranger Supertramp",
  "Shooting Star Bad Company",
  "Love Her Madly Doors",
  "Touch of Grey Grateful Dead",
  "Flying High Again Ozzy Osbourne",
  "Take The Money And Run Steve Miller",
  "Don't Look Back Boston",
  "Have A Drink On Me AC/DC",
  "Speak To Me/Breathe Pink Floyd",
  "Run To You Bryan Adams",
  "Right Now Van Halen",
  "Sledgehammer Peter Gabriel",
  "I Won't Back Down Tom Petty",
  "Subdivisions Rush",
  "My Hero Foo Fighters",
  "Let My Love Open The Door Pete Townshend",
  "Rebel Rebel David Bowie",
  "Armageddon It Def Leppard",
  "Love Hurts Nazareth",
  "Girls Got Rhythm AC/DC",
  "Tumbling Dice Rolling Stones",
  "One Bourbon, One Scotch, One Beer George Thorogood",
  "Authority Song John Mellencamp",
  "Don't Stand So Close To Me Police",
  "Shine Collective Soul",
  "Crossfire Stevie Ray Vaughan",
  "Knockin' On Heaven's Door Guns N' Roses",
  "Crazy On You Heart",
  "Feel Your Love Tonight Van Halen",
  "Have a Cigar Pink Floyd",
  "Modern Love David Bowie",
  "I Can't Drive 55 Sammy Hagar",
  "China Grove Doobie Brothers",
  "The Ocean Led Zeppelin",
  "Moving In Stereo Cars",
  "Love Bites Def Leppard",
  "Kickstart My Heart Motley Crue",
  "Fire Jimi Hendrix",
  "The One I Love R.E.M.",
  "Back In the Saddle Aerosmith",
  "Hold On Loosely 38 Special",
  "Touch Me Doors",
  "War Pigs Black Sabbath",
  "Rockin' In The Free World Neil Young",
  "Rock & Roll Hoochie Coo Rick Derringer",
  "Dancing With Myself Billy Idol",
  "What's Your Name Lynyrd Skynyrd",
  "Cult Of Personality Living Colour",
  "Refugee Tom Petty",
  "Let's Get It Up AC/DC",
  "Plush Stone Temple Pilots",
  "Keep Your Hands To Yourself Georgia Satellites",
  "Stranglehold Ted Nugent",
  "Mysterious Ways U2",
  "Should I Stay Or Should I Go Clash",
  "Silent Lucidity Queensrÿche",
  "Good Times Bad Times Led Zeppelin",
  "Caught Up In You 38 Special",
  "Saturday Night's Alright For Fighting Elton John",
  "Working For The Weekend Loverboy",
  "Finish What Ya Started Van Halen",
  "Once In A Lifetime Talking Heads",
  "I Don't Know Ozzy Osbourne",
  "Fly By Night Rush",
  "Walking On The Moon Police",
  "Gimme All Your Lovin' ZZ Top",
  "Bringin' On The Heartbreak Def Leppard",
  "Doo Doo Doo Doo (Heartbreaker) Rolling Stones",
  "Cuts Like a Knife Bryan Adams",
  "All Night Long Joe Walsh",
  "It's The End Of The World As We Know It  R.E.M.",
  "Don't Do Me Like That Tom Petty",
  "Rock And Roll Band Boston",
  "Against The Wind Bob Seger",
  "Live And Let Die Guns N' Roses",
  "Fly Like An Eagle Steve Miller",
  "Cryin' Aerosmith",
  "Living After Midnight Judas Priest",
  "Misty Mountain Hop Led Zeppelin",
  "Two Tickets To Paradise Eddie Money",
  "Give It Away Red Hot Chili Peppers",
  "Brass In Pocket Pretenders",
  "Is This Love Whitesnake",
  "Fame David Bowie",
  "Love Stinks J. Geils Band",
  "Runaway Bon Jovi",
  "Us And Them Pink Floyd",
  "Dirty Laundry Don Henley",
  "That Smell Lynyrd Skynyrd",
  "Hot For Teacher Van Halen",
  "You Might Think Cars",
  "Over the Mountain Ozzy Osbourne",
  "Twilight Zone Golden Earring",
  "Even Flow Pearl Jam",
  "No More Mr. Nice Guy Alice Cooper",
  "Unchained Van Halen",
  "Mony Mony Billy Idol",
  "Love Is a Battlefield Pat Benatar",
  "Pink Houses John Mellencamp",
  "Moneytalks AC/DC",
  "Logical Song Supertramp",
  "Too Much Time On My Hands Styx",
  "Mary Jane's Last Dance Tom Petty",
  "Lights Journey",
  "Foolin' Def Leppard",
  "We're An American Band Grand Funk Railroad",
  "Black Hole Sun Soundgarden",
  "Jungle Love Steve Miller",
  "All My Love Led Zeppelin",
  "Every Little Thing She Does Is Magic Police",
  "Man In the Box Alice In Chains",
  "After Midnight Eric Clapton",
  "Turn Up the Radio Autograph",
  "Beautiful Day U2",
  "Hollywood Nights Bob Seger",
  "Blue On Black Kenny Wayne Sheppard",
  "Take Me Home Tonight Eddie Money",
  "Learn To Fly Foo Fighters",
  "Owner Of A Lonely Heart Yes",
  "December Collective Soul",
  "Cheap Sunglasses ZZ Top",
  "You Can Still Rock In America Night Ranger",
  "Heat of the Moment Asia",
  "She Talks To Angels Black Crowes",
  "Straight On Heart",
  "Hurts So Good John Mellencamp",
  "Patience Guns N' Roses",
  "Crazy Little Thing Called Love Queen",
  "Bad Case of Lovin' You Robert Palmer",
  "Centerfield John Fogerty",
  "Rockin' Into the Night 38 Special",
  "Trampled Under Foot Led Zeppelin",
  "Dude (Looks Like A Lady) Aerosmith",
  "Good Riddance Green Day",
  "Shakin' Eddie Money",
  "Nothin' But A Good Time Poison",
  "Free Ride Edgar Winter Group",
  "Stop Draggin' My Heart Around Stevie Nicks/Tom Petty",
  "I Wanna Rock Twisted Sister",
  "You Got Lucky Tom Petty",
  "Big Balls AC/DC",
  "What It Takes Aerosmith",
  "Jane Jefferson Starship",
  "Time For Me To Fly REO Speedwagon",
  "18 & Life Skid Row",
  "All Right Now Free",
  "Smokin'   Boston",
  "All Apologies Nirvana",
  "The Fire Down Below Bob Seger",
  "Abacab Genesis",
  "Black Water Doobie Brothers",
  "Synchronicity II Police",
  "People Are Strange Doors",
  "Addicted To Love Robert Palmer",
  "Round and Round Ratt",
  "Stone In Love Journey",
  "Rock & Roll Ain't Noise Pollution AC/DC",
  "Take The Long Way Home Supertramp",
  "Smokin' In The Boys Room Mötley Crüe",
  "She's a Beauty Tubes",
  "Middle Of The Road Pretenders",
  "Bad Medicine Bon Jovi",
  "The Waiting Tom Petty",
  "Animal Def Leppard",
  "When I Come Around Green Day",
  "Can't Get Enough Bad Company",
  "There's Only One Way To Rock Sammy Hagar",
  "Call Me Blondie",
  "Hair Of The Dog Nazareth",
  "Dancing Days Led Zeppelin",
  "Urgent Foreigner",
  "Her Strut Bob Seger",
  "November Rain Guns N' Roses",
  "Lunatic Fringe Red Rider",
  "Welcome To The Machine Pink Floyd",
  "Move It On Over George Thorogood",
  "Roll With The Changes REO Speedwagon",
  "Life During Wartime Talking Heads",
  "Black Betty Ram Jam",
  "R.O.C.K. In The U.S.A. John Mellencamp",
  "Signs Tesla",
  "Here Comes My Girl Tom Petty",
  "Gold Dust Woman Fleetwood Mac",
  "Glory Days Bruce Springsteen",
  "Lovin', Touchin', Squeezin' Journey",
  "Bang Your Head Quiet Riot",
  "You Wreck Me Tom Petty",
  "Feelin' Satisfied Boston",
  "Train In Vain Clash",
  "Dreams Van Halen",
  "Slow Ride Foghat",
  "Better Man Pearl Jam",
  "The Breakup Song Greg Kihn Band",
  "Hysteria Def Leppard",
  "Low Rider War ",
  "Janie's Got A Gun Aerosmith",
  "Hello, I Love You Doors",
  "I Don't Care Anymore Phil Collins",
  "What Is And What Should Never Be Led Zeppelin",
  "Spirits In the Material World Police",
  "Swingtown Steve Miller",
  "My Kinda Lover Billy Squier",
  "Wind Of Change Scorpions",
  "Shattered Rolling Stones",
  "American Woman Guess Who",
  "You're All I've Got Tonight Cars",
  "Takin' Care Of Business Bachman-Turner Overdrive",
  "Everybody Wants Some!! Van Halen"
]
